//
//  ServerServices.swift

//  Automatically created by ServicesFromWSDL.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a wsdl definitions wsdl file)
// Edit the source data and then use the ServicesFromWSDL
// to create the corresponding services files automatically

import Foundation

/// all connectors to a soap service must conform to this protocol
public protocol ServerServicesConnector {
    func callWSDLFunction(named functionName: String, parameters: [String: Any]?, in serviceName: String, completion: ((Any?, Error?) -> Void)?)
}
